// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjpsOvEIJq91zSEWnAHYFGyC7c6e-blh4',
    appId: '1:909914474747:web:c9eb58b9a9119c012f085e',
    messagingSenderId: '909914474747',
    projectId: 'jobber-city-app',
    authDomain: 'jobber-city-app.firebaseapp.com',
    storageBucket: 'jobber-city-app.firebasestorage.app',
    measurementId: 'G-RZVFDEN7B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsGvg3l_N1zqfq0n6dWiXp4l1Wt-6hhnI',
    appId: '1:909914474747:android:c0a9b4a3880ed2d32f085e',
    messagingSenderId: '909914474747',
    projectId: 'jobber-city-app',
    storageBucket: 'jobber-city-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCddHfaXpv2M4TWtPlMiklf0_0TT3J-xo',
    appId: '1:909914474747:ios:69a4ed95e85a26462f085e',
    messagingSenderId: '909914474747',
    projectId: 'jobber-city-app',
    storageBucket: 'jobber-city-app.firebasestorage.app',
    iosBundleId: 'com.example.jobberCity',
  );
}
